name: My first Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: macos
            needs_installer: true
          - os: ubuntu-latest
            artifact_name: linux
            needs_installer: false
          - os: windows-latest
            artifact_name: windows
            needs_installer: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Build binary
        run: pyinstaller --onefile main.py
          
      - name: Upload binary with installer
        if: matrix.needs_installer
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.artifact_name }}
          path: |
            dist/*
            install.sh

      - name: Upload binary without installer
        if: "!matrix.needs_installer"
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.artifact_name }}
          path: dist/*
  
  
    
