name: EXE builder
on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  MyFirstJob:
    runs-on: macos-latest
    
    steps:
      - name: Say Hello
        run: echo "👋 Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
      
      - name: Verify Python version
        run: |
          python --version
          which python
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pywebview
      
      - name: Build with PyInstaller
        run: |
          pyinstaller hello.spec
      
      - name: Prepare artifact
        if: runner.os == 'macOS'
        run: |
          cd dist
          chmod +x hello
          tar czf hello.tar.gz hello
          cat > install.sh << 'EOF'
          #!/bin/bash
          # Simple installer for hello application
          
          # Get the directory of this script
          SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
          
          # Extract the executable
          tar xzf "$SCRIPT_DIR/hello.tar.gz"
          
          # Remove quarantine attribute
          xattr -d com.apple.quarantine hello 2>/dev/null || true
          
          # Make executable
          chmod +x hello
          
          echo "Installation complete! You can now run ./hello"
          EOF
          chmod +x install.sh
          tar czf hello_with_installer.tar.gz hello.tar.gz install.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello_with_installer.tar.gz
          path: dist/hello_with_installer.tar.gz
          compression-level: 0
  
  
    
