name: EXE builder
on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  MyFirstJob:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Get version
        id: version
        run: |
          # Read major.minor from version.txt
          BASE_VERSION=$(cat version.txt)
          # Get number of commits for patch version
          PATCH=$(git rev-list --count HEAD)
          # Combine them (ensure no spaces)
          VERSION="${BASE_VERSION// /}.${PATCH}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pywebview
      
      - name: Build with PyInstaller
        run: |
          pyinstaller hello.spec
      
      - name: Prepare artifact
        if: runner.os == 'macOS'
        run: |
          cd dist
          chmod +x hello
          cat > install.sh << 'EOF'
          #!/bin/bash
          # Simple installer for hello application v${{ steps.version.outputs.version }}
          
          # Remove quarantine attribute
          xattr -d com.apple.quarantine hello 2>/dev/null || true
          
          # Make executable
          chmod +x hello
          
          echo "Installation complete! You can now run ./hello"
          EOF
          chmod +x install.sh

      - name: Create Git tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push --tags

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello-${{ steps.version.outputs.version }}-macos
          path: |
            dist/hello
            dist/install.sh
  
  
    
